FROM gcr.io/forgerock-io/java-11:latest

COPY IG-sample-application-7.0.1.jar /home/IG-sample-application-7.0.1.jar

EXPOSE 8888 8889
CMD ["java","-jar","/home/IG-sample-application-7.0.1.jar", "8888", "8889"]