ARG registry=sandbox
ARG docker_tag=7.1.0
FROM ${registry}/ds-base:${docker_tag}
USER root
RUN chown -R forgerock:root /opt/opendj
USER forgerock
COPY --chown=forgerock:root common  /opt/opendj/
COPY --chown=forgerock:root cts     /opt/opendj/
COPY --chown=forgerock:root scripts /opt/opendj/scripts
ARG profile_version
RUN bin/setup.sh && \
    bin/relax-security-settings.sh  && \
    rm bin/setup.sh bin/relax-security-settings.sh

ENTRYPOINT [ "/opt/opendj/customise.sh" ]