
version: "3.5"

x-common-variables-properties: &platform-properties
    - AM_URL=https://${FQDN}/am
    - AM_ADMIN_URL=https://${FQDN}/am/ui-admin/
    - IDM_REST_URL=https://${FQDN}/openidm
    - IDM_ADMIN_URL=https://${FQDN}/admin
    - IDM_UPLOAD_URL=https://${FQDN}/upload
    - IDM_EXPORT_URL=https://${FQDN}/export
    - LOGIN_UI_URL=https://${FQDN}/login/#/service/PlatformLogin
    - ENDUSER_UI_URL=https://${FQDN}/enduser
    - PLATFORM_ADMIN_URL=https://${FQDN}/platform
    - ENDUSER_CLIENT_ID=end-user-ui
    - ADMIN_CLIENT_ID=idm-admin-ui
    - THEME=default
    - PLATFORM_UI_LOCALE=en

services:
  idrepo:
    build: 
      context: $DOCKER/ds
      dockerfile: $DOCKER/ds/idrepo/Dockerfile
    image: ${REGISTRY}/ds-idrepo:${DS_VERSION}
    container_name: idrepo.local
    environment:
      - DS_SET_UID_ADMIN_AND_MONITOR_PASSWORDS=true
      - DS_UID_ADMIN_PASSWORD=password
      - DS_UID_MONITOR_PASSWORD=password
    ports:
      - 389:1389
    volumes:
      - idrepodata:/opt/opendj/data
      - ./security/ds:/opt/opendj/secrets
    command: start-ds

  postgres:
    build: $DOCKER/postgres
    container_name: postgres.local
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  cts:
    build: 
      context: $DOCKER/ds
      dockerfile: $DOCKER/ds/cts/Dockerfile
    image: ${REGISTRY}/ds-cts:${DS_VERSION}
    container_name: cts.local
    ports:
      - 1389:1389
    environment:
      - DS_SET_UID_ADMIN_AND_MONITOR_PASSWORDS=true
      - DS_UID_ADMIN_PASSWORD=password
      - DS_UID_MONITOR_PASSWORD=password
    command: start-ds
    volumes:
      - ctsdata:/opt/opendj/data
      - ./security/ds:/opt/opendj/secrets
  
  am:
    build: $DOCKER/am
    image: ${REGISTRY}/am:${VERSION}
    container_name: ${AM_CONTAINER}
    ports:
      - 8080:8080
    depends_on:
      - cts
      - idrepo
    volumes:
      - ./security/am:/var/run/secrets
      # - ../../config/stage:/home/forgerock/shared
    environment:
      - AM_STORES_USER_SERVERS=idrepo:1389
      - AM_STORES_USER_CONNECTION_MODE=ldap
      - AM_STORES_CTS_SERVERS=cts:1389
      - AM_STORES_SSL_ENABLED=false
      - AM_PASSWORDS_AMADMIN_CLEAR=password
      - FQDN=${FQDN}
      - AM_SERVER_FQDN=${FQDN}
      - AM_ENCRYPTION_KEY=C00lbeans
      - PLATFORM_UI_IS_FRAAS=false
      - VERSION=${VERSION}

  impexp:
    image: ${REGISTRY}/impexp
    build:
      context: $DOCKER/impexp
      args:
        - docker_tag=${VERSION}
        - registry=${REGISTRY}
    container_name: ${EXPORTER_CONTAINER}
    environment:
      - FQDN=${FQDN}
    volumes:
      - ./security/amster:/var/run/secrets
    command: import-export

  idm:
    build: $DOCKER/idm
    image: ${REGISTRY}/idm:${VERSION}
    container_name: ${IDM_CONTAINER}
    volumes:
      - ./security/idm:/var/run/secrets/idm
      - ./csvfiles:/opt/openidm/csvfiles
    ports:
      - 8082:8080
    environment:
      # - OPENIDM_REPO_HOST=idrepo
      # - OPENIDM_REPO_PORT=1389
      - OPENIDM_REPO_HOST=postgres
      - OPENIDM_REPO_PORT=5432
      - OPENIDM_REPO_PASSWORD=password
      - OPENIDM_KEYSTORE_LOCATION=/var/run/secrets/idm/keystore.jceks
      - OPENIDM_TRUSTSTORE_LOCATION=/var/run/secrets/idm/truststore
    depends_on:
      - idrepo

  adminUI:
    image: gcr.io/forgerock-io/platform-admin-ui:7.4.0
    container_name: adminui.local
    environment: *platform-properties
  
  enduserUI:
    image: gcr.io/forgerock-io/platform-enduser-ui:7.4.0
    container_name: enduserui.local
    environment: *platform-properties

  loginUI:
    image: gcr.io/forgerock-io/platform-login-ui:7.4.0
    container_name: loginui.local
    environment: *platform-properties

  nginx:
    image: nginx
    container_name: nginx.local
    ports:
      - 443:443
    depends_on:
      # - idm
      - am
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/certs/platform.crt:/etc/nginx/ssl.crt
      - ./nginx/certs/platform-key.pem:/etc/nginx/ssl-key.pem
    environment:
      - SERVER_NAME=$FQDN
    command: /bin/bash -c "envsubst '$${SERVER_NAME} $${AM_FQDN}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        
volumes:
  shared:
  idrepodata:
  ctsdata:
  pgdata: